### ISSUE TITLE
Some general questions about end to end testing

### ISSUE THREAD

**Issue by rm-bergmann** [AmazeeLabs/bdd-gatsby-cypress#1]
Thank you for taking the time to show us your End to end testing workflow with Cypress and Gatsby! I enjoyed it and I learned a lot.

Now that I have been experimenting with these workflows in my project I have thought about a few questions which would be great to get your suggestions on.
 
 
1. Do your clients have any interface for running the end to end tests or viewing the results and screenshots? Or do only developers access the tests which are run on deployment?
 
2. Can you have multiple 'Given' statements in 1 {featureName}.feature file and 1 {featureName}.js file? For example: Given a user lands on an English page.... Then test the same functionality but different expectations on a French page.
	 
3. I tried to test basic a scenario where user clicking on a specific link that redirects to an external url. Cypress always fails the test, despite the screenshots show that cypress is redirected to that external url. Is there a better way to test this?
 
4. As you mentioned in the webinar, it’s not good practice to find elements using classnames or ID's, and should be written as the client would read and understand. -  In order to achieve this I am currently getting the parent div container with a class name then finding the button that contains the text that the user should see. 
	 
- For example: `cy.get('.classname').find('button').contains('click me')`

Is this the best way to do that or can it be improved?
 
5. I have used the Lagoon project before and I saw you have Percy as a package or extension to your cypress workflow.  What benefits do you gain from Percy.io?

Thanks in advance!
Rick.

**Comment by pmelab** [comment]
Hi Rick! Thanks for your interest 😄 

> Do your clients have any interface for running the end to end tests or viewing the results and screenshots? Or do only developers access the tests which are run on deployment?

Most of the time its just developers in our case. Clients could technically *run* them if they have access to the CI/CD service (e.g. Travis). Nobody ever requested that since we run them on every commit and on a scheduled basis anyway.

Cypress is offering the [Cypress Dashboard](https://www.cypress.io/dashboard/) as a paid service. That's an easy way to expose test results, videos and screenshots to clients and managers (I am *not* on their payroll 😄). A free alternative would be to just copy the results onto some storage service and access them from there.

> Can you have multiple 'Given' statements in 1 {featureName}.feature file and 1 {featureName}.js file? For example: Given a user lands on an English page.... Then test the same functionality but different expectations on a French page.

You would use match patterns for that. This step definition...

```
Given(/^a user lands on an? (.*?) page$/, lang => {
  ...
});
```

... will match both of these sentences and execute with `lang` set to the respective value:

```
Given a user lands on an English page

...

Given a user lands on a French page
```


> I tried to test basic a scenario where user clicking on a specific link that redirects to an external url. Cypress always fails the test, despite the screenshots show that cypress is redirected to that external url. Is there a better way to test this?

Cypress currently has a limitation that only allows one domain per test. Also you should only test your own application. If the external website goes down, your tests will break even though nothing is wrong with your code.

I see two ways to solve this:

1. Easy: Instead of clicking the link, just check if the `href` attribute is what you would expect. For the rest you just trust the internet still works :)
2. Fancy: You could somehow block the browser navigation behavior (click handler on all links?) and instead of actually navigating, globally track where the user *would* end up. And then you can use this value to check if it is the correct address.

> As you mentioned in the webinar, it’s not good practice to find elements using classnames or ID's, and should be written as the client would read and understand. -  In order to achieve this I am currently getting the parent div container with a class name then finding the button that contains the text that the user should see.

I always prefer to bind tests to something the user actually _sees_. In your case this would be the button text. [Cypress testing library](https://github.com/testing-library/cypress-testing-library) provides a lot of useful functions for that, like `findByText`, `findByLabelText` etc. And if your element is not targettable by text that is at least visible to a screenreader, you have an accessibility problem 😉 .

> I have used the Lagoon project before and I saw you have Percy as a package or extension to your cypress workflow.  What benefits do you gain from Percy.io?

Percy is a visual regression tool that tracks how the user interface changes based on screenshots and allows clients/managers/designers to quickly look at changes and confirm or reject them. If this is not required for a project, we fall back to [Loki](https://loki.js.org/). Or we even use them in combination.

I hope that helped! Cheers!

**Comment by rm-bergmann** [comment]
Yes this is all very helpful, thank you!

> Easy: Instead of clicking the link, just check if the href attribute is what you would expect. For the rest you just trust the internet still works :)

That is the approach I am using already, because I am just testing that the correct URL is being generated on the page so I will continue using that approach.

Sounds like Percy will be a good solution to my no.1 question in that case, if I want non developers within the team or business to view screenshots generated by Cypress.

**Comment by rm-bergmann** [comment]
Hi @pmelab 

How do you use multiple arguments within a given statement? 

```
Given(/^a user creates a page and sets the brand to? (.*?) and language to? (.*?) $/, (brand, language) => {
  cy.setPageBrandAndLanguage(brand, language)
});
```

The error I get:
```
Step implementation missing for: a user creates a page and sets the brand to [brandname] and language to French
```

I have been reading the cucumber docs and I have searched and the best I found so far is [this article](https://centricconsulting.com/blog/using-parameters-in-bdd-gherkin-script_sqat-columbus/), but the example is written in a different way. I can't find a similar example in this repo.

Thanks in advance.

**Comment by rm-bergmann** [comment]
I had some time to come back to this and do some debugging. It took me far too long to notice but the reason I got the error was because there was a space here: ` (.*?) $/` and the above code works for multiple arguments, or alternatively some might prefer to have 1 argument and 2 steps.

On the upside, after reading all the cucumber documentation I discovered a slightly syntax friendlier way of writing the above (but currently only have it working with 1 argument and I get the same error as above, but could be a typo. I'll test again later).

`
Given(`a user creates a page and sets the brand to {strring}`, (brand) => {
  // execute cy command
});`
`
